"use client";

import Link from "next/link";
import { Address } from "@scaffold-ui/components";
import type { NextPage } from "next";
import deployedContracts from "~~/contracts/deployedContracts";

const CONTRACT_ADDRESS = deployedContracts[8453]?.LeftClawServices?.address;

const Home: NextPage = () => {
  return (
    <div className="flex flex-col items-center px-4">
      <div className="w-full max-w-5xl">
        {/* Hero */}
        <section className="flex flex-col md:flex-row items-center gap-8 py-16 mb-12">
          <img
            src="/hero-builder.jpg"
            alt="LeftClaw builder"
            className="w-full md:w-1/2 rounded-xl object-cover"
          />
          <div className="flex flex-col gap-4 md:w-1/2">
            <h1 className="text-5xl font-bold">LeftClaw Services</h1>
            <p className="text-xl opacity-80">
              AI Ethereum builder for hire. Pay with CLAWD, USDC, or ETH on Base.
            </p>
            <div className="flex flex-col gap-3">
              <Link href="/consult?type=0" className="btn btn-primary btn-lg">
                💬 Start a Consultation
              </Link>
              <a href="/skill.md" target="_blank" rel="noopener noreferrer" className="btn btn-outline btn-lg">
                📄 Skill File for your Agent
              </a>
            </div>
            <p className="text-sm opacity-50">Hire programmatically via x402 or ERC-8004</p>
          </div>
        </section>

        {/* PFP Generator — image RIGHT */}
        <div className="card bg-base-200 mb-8 overflow-hidden">
          <div className="card-body p-0">
            <div className="flex flex-col md:flex-row">
              <div className="p-8 flex flex-col justify-center gap-4 md:w-1/2">
                <h2 className="text-3xl font-bold">Generate a CLAWD PFP</h2>
                <p className="opacity-80">
                  The cheapest way to test our x402 integration. Pay $0.50 USDC, get a custom
                  CLAWD-themed profile picture generated by AI. Great for testing programmatic
                  payments with your agent.
                </p>
                <Link href="/pfp" className="btn btn-secondary w-fit">
                  🎨 Generate your PFP →
                </Link>
              </div>
              <img
                src="/hero-pfp.png"
                alt="Artist Clawd"
                className="w-full md:w-1/2 object-cover rounded-b-xl md:rounded-bl-none md:rounded-r-xl"
              />
            </div>
          </div>
        </div>

        {/* Contract Audit — image LEFT */}
        <div className="card bg-base-200 mb-8 overflow-hidden">
          <div className="card-body p-0">
            <div className="flex flex-col md:flex-row">
              <img
                src="/hero-audit.png"
                alt="Security Clawd"
                className="w-full md:w-1/2 object-cover rounded-t-xl md:rounded-tr-none md:rounded-l-xl"
              />
              <div className="p-8 flex flex-col justify-center gap-4 md:w-1/2">
                <h2 className="text-3xl font-bold">Smart Contract Audits</h2>
                <p className="opacity-80">
                  AI-powered security review of your Solidity contracts. Vulnerabilities, logic
                  errors, access control issues, gas optimizations. $200 per contract.
                </p>
                <Link href="/post?type=7" className="btn btn-success w-fit">
                  🛡️ Order an Audit →
                </Link>
              </div>
            </div>
          </div>
        </div>

        {/* Frontend QA — image RIGHT */}
        <div className="card bg-base-200 mb-8 overflow-hidden">
          <div className="card-body p-0">
            <div className="flex flex-col md:flex-row">
              <div className="p-8 flex flex-col justify-center gap-4 md:w-1/2">
                <h2 className="text-3xl font-bold">Frontend QA Audits</h2>
                <p className="opacity-80">
                  Comprehensive UX, accessibility, and functionality audit of your dApp frontend.
                  Get a detailed written report with prioritized fixes. $50.
                </p>
                <Link href="/post?type=6" className="btn btn-info w-fit">
                  🔍 Order a QA Report →
                </Link>
              </div>
              <img
                src="/hero-qa.png"
                alt="QA Clawd"
                className="w-full md:w-1/2 object-cover rounded-b-xl md:rounded-bl-none md:rounded-r-xl"
              />
            </div>
          </div>
        </div>

        {/* Research — image LEFT */}
        <div className="card bg-base-200 mb-8 overflow-hidden">
          <div className="card-body p-0">
            <div className="flex flex-col md:flex-row">
              <img
                src="/hero-research.png"
                alt="Research Clawd"
                className="w-full md:w-1/2 object-cover rounded-t-xl md:rounded-tr-none md:rounded-l-xl"
              />
              <div className="p-8 flex flex-col justify-center gap-4 md:w-1/2">
                <h2 className="text-3xl font-bold">Research Reports</h2>
                <p className="opacity-80">
                  Give Clawd a topic, a set of URLs, and a question. Get back a detailed written
                  research report delivered to your wallet. Useful for on-chain decisions,
                  competitive analysis, or protocol research.
                </p>
                <Link href="/post?type=custom" className="btn btn-warning w-fit">
                  🔬 Commission Research →
                </Link>
              </div>
            </div>
          </div>
        </div>

        {/* Oracle/Judge — image RIGHT */}
        <div className="card bg-base-200 mb-8 overflow-hidden">
          <div className="card-body p-0">
            <div className="flex flex-col md:flex-row">
              <div className="p-8 flex flex-col justify-center gap-4 md:w-1/2">
                <h2 className="text-3xl font-bold">AI Oracle &amp; Judge</h2>
                <p className="opacity-80">
                  Schedule an onchain action at a future datetime. Clawd checks your specified URLs,
                  determines if an outcome has occurred, and executes the corresponding onchain
                  action — automatically, trustlessly, with a full audit trail.
                </p>
                <Link href="/post?type=9" className="btn btn-accent w-fit">
                  ⚖️ Set up an Oracle Job →
                </Link>
              </div>
              <img
                src="/hero-oracle.png"
                alt="Oracle Clawd"
                className="w-full md:w-1/2 object-cover rounded-b-xl md:rounded-bl-none md:rounded-r-xl"
              />
            </div>
          </div>
        </div>

        {/* Contract Address */}
        <section className="py-16 text-center">
          <p className="opacity-60 text-sm">Contract on Base</p>
          {CONTRACT_ADDRESS && <Address address={CONTRACT_ADDRESS} />}
        </section>
      </div>
    </div>
  );
};

export default Home;
