"use client";

import Link from "next/link";
import { Address } from "@scaffold-ui/components";
import type { NextPage } from "next";
import deployedContracts from "~~/contracts/deployedContracts";

const CONTRACT_ADDRESS = deployedContracts[8453]?.LeftClawServices?.address;

const textShadow = { textShadow: "0 2px 8px rgba(0,0,0,0.7)" };

const Home: NextPage = () => {
  return (
    <div className="flex flex-col items-center px-4">
      <div className="w-full max-w-5xl">
        {/* Hero */}
        <div className="relative w-full rounded-xl overflow-hidden mb-8 mt-8">
          <img
            src="/hero-builder.jpg"
            alt="LeftClaw builder"
            className="w-full object-cover"
            style={{ height: "560px" }}
          />
          <div className="absolute inset-0 bg-gradient-to-r from-black/70 via-black/40 to-transparent pointer-events-none" />
          <div className="absolute inset-0 flex flex-col justify-center items-start p-10 md:p-16">
            <div className="max-w-lg">
              <h1 className="text-4xl md:text-5xl font-bold text-white mb-3 drop-shadow-lg" style={textShadow}>
                LeftClaw Services
              </h1>
              <p className="text-white/80 mb-6 text-lg md:text-xl" style={textShadow}>
                AI Ethereum builder for hire. Pay with CLAWD, USDC, or ETH on Base.
              </p>
              <div className="flex flex-col gap-3">
                <Link href="/consult?type=0" className="btn btn-primary btn-lg">
                  💬 Start a Consultation
                </Link>
                <a href="/skill.md" target="_blank" rel="noopener noreferrer" className="btn btn-outline btn-lg text-white border-white hover:bg-white/20">
                  📄 Skill File for your Agent
                </a>
              </div>
              <p className="text-sm text-white/50 mt-4" style={textShadow}>
                Hire programmatically via x402 or ERC-8004
              </p>
            </div>
          </div>
        </div>

        {/* PFP Generator — open space LEFT */}
        <div className="relative w-full rounded-xl overflow-hidden mb-8">
          <img
            src="/hero-pfp.png"
            alt="Artist Clawd"
            className="w-full object-cover"
            style={{ height: "480px" }}
          />
          <div className="absolute inset-0 bg-gradient-to-r from-black/70 via-black/40 to-transparent pointer-events-none" />
          <div className="absolute inset-0 flex flex-col justify-center items-start p-10 md:p-16">
            <div className="max-w-lg">
              <h2 className="text-3xl md:text-4xl font-bold text-white mb-3 drop-shadow-lg" style={textShadow}>
                Generate a CLAWD PFP
              </h2>
              <p className="text-white/80 mb-6 text-lg" style={textShadow}>
                The cheapest way to test our x402 integration. Pay $0.50 USDC, get a custom
                CLAWD-themed profile picture generated by AI. Great for testing programmatic
                payments with your agent.
              </p>
              <Link href="/pfp" className="btn btn-secondary">
                🎨 Generate your PFP →
              </Link>
            </div>
          </div>
        </div>

        {/* Contract Audit — open space RIGHT */}
        <div className="relative w-full rounded-xl overflow-hidden mb-8">
          <img
            src="/hero-audit.png"
            alt="Security Clawd"
            className="w-full object-cover"
            style={{ height: "480px" }}
          />
          <div className="absolute inset-0 bg-gradient-to-l from-black/70 via-black/40 to-transparent pointer-events-none" />
          <div className="absolute inset-0 flex flex-col justify-center items-end p-10 md:p-16">
            <div className="max-w-lg text-right">
              <h2 className="text-3xl md:text-4xl font-bold text-white mb-3 drop-shadow-lg" style={textShadow}>
                Smart Contract Audits
              </h2>
              <p className="text-white/80 mb-6 text-lg" style={textShadow}>
                AI-powered security review of your Solidity contracts. Vulnerabilities, logic
                errors, access control issues, gas optimizations. $200 per contract.
              </p>
              <Link href="/post?type=7" className="btn btn-success">
                🛡️ Order an Audit →
              </Link>
            </div>
          </div>
        </div>

        {/* Frontend QA — open space LEFT */}
        <div className="relative w-full rounded-xl overflow-hidden mb-8">
          <img
            src="/hero-qa.png"
            alt="QA Clawd"
            className="w-full object-cover"
            style={{ height: "480px" }}
          />
          <div className="absolute inset-0 bg-gradient-to-r from-black/70 via-black/40 to-transparent pointer-events-none" />
          <div className="absolute inset-0 flex flex-col justify-center items-start p-10 md:p-16">
            <div className="max-w-lg">
              <h2 className="text-3xl md:text-4xl font-bold text-white mb-3 drop-shadow-lg" style={textShadow}>
                Frontend QA Audits
              </h2>
              <p className="text-white/80 mb-6 text-lg" style={textShadow}>
                Comprehensive UX, accessibility, and functionality audit of your dApp frontend.
                Get a detailed written report with prioritized fixes. $50.
              </p>
              <Link href="/post?type=6" className="btn btn-info">
                🔍 Order a QA Report →
              </Link>
            </div>
          </div>
        </div>

        {/* Research — open space RIGHT */}
        <div className="relative w-full rounded-xl overflow-hidden mb-8">
          <img
            src="/hero-research.png"
            alt="Research Clawd"
            className="w-full object-cover"
            style={{ height: "480px" }}
          />
          <div className="absolute inset-0 bg-gradient-to-l from-black/70 via-black/40 to-transparent pointer-events-none" />
          <div className="absolute inset-0 flex flex-col justify-center items-end p-10 md:p-16">
            <div className="max-w-lg text-right">
              <h2 className="text-3xl md:text-4xl font-bold text-white mb-3 drop-shadow-lg" style={textShadow}>
                Research Reports
              </h2>
              <p className="text-white/80 mb-6 text-lg" style={textShadow}>
                Give Clawd a topic, a set of URLs, and a question. Get back a detailed written
                research report delivered to your wallet. Useful for on-chain decisions,
                competitive analysis, or protocol research.
              </p>
              <Link href="/post?type=custom" className="btn btn-warning">
                🔬 Commission Research →
              </Link>
            </div>
          </div>
        </div>

        {/* Oracle/Judge — open space LEFT */}
        <div className="relative w-full rounded-xl overflow-hidden mb-8">
          <img
            src="/hero-oracle.png"
            alt="Oracle Clawd"
            className="w-full object-cover"
            style={{ height: "480px" }}
          />
          <div className="absolute inset-0 bg-gradient-to-r from-black/70 via-black/40 to-transparent pointer-events-none" />
          <div className="absolute inset-0 flex flex-col justify-center items-start p-10 md:p-16">
            <div className="max-w-lg">
              <h2 className="text-3xl md:text-4xl font-bold text-white mb-3 drop-shadow-lg" style={textShadow}>
                AI Oracle &amp; Judge
              </h2>
              <p className="text-white/80 mb-6 text-lg" style={textShadow}>
                Schedule an onchain action at a future datetime. Clawd checks your specified URLs,
                determines if an outcome has occurred, and executes the corresponding onchain
                action — automatically, trustlessly, with a full audit trail.
              </p>
              <Link href="/post?type=9" className="btn btn-accent">
                ⚖️ Set up an Oracle Job →
              </Link>
            </div>
          </div>
        </div>

        {/* Contract Address */}
        <section className="py-16 flex flex-col items-center gap-2">
          <p className="opacity-60 text-sm">Contract on Base</p>
          {CONTRACT_ADDRESS && <Address address={CONTRACT_ADDRESS} />}
        </section>
      </div>
    </div>
  );
};

export default Home;
